<?php
/**
 * Yireo GoogleTranslate for Magento
 *
 * @package     Yireo_GoogleTranslate
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$widget_css = null;
if(Mage::getStoreConfig('catalog/googletranslate/widget_fixed') == 1) {
    $widget_css = 'position:fixed; bottom:0; width:100%;';
}
?>
<div class="googletranslate-widget" style="<?php echo $widget_css; ?>">
    <div class="heading">
        <strong><?php echo $this->__('GoogleTranslate configuration'); ?>:</strong>
    </div>

    <div class="field">
        <label for="googletranslate_source_language"><?php echo $this->__('Source language'); ?></label>
        <select id="googletranslate_source_language" name="googletranslate_source_language" onchange="return googletranslate_change();">
            <option value="auto"><?php echo $this->__('Automatic'); ?></option>
            <?php foreach($this->getLanguages() as $language) : ?>
                <?php $selected = ($this->getSourceLanguage() == $language['value']) ? 'selected="selected"' : null; ?>
                <option value="<?php echo $language['value']; ?>" <?php echo $selected; ?>><?php echo $language['label']; ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="field">
        <label for="googletranslate_destination_language"><?php echo $this->__('Destination language'); ?></label>
        <select id="googletranslate_destination_language" name="googletranslate_destination_language" onchange="return googletranslate_change();">
            <option value="auto"><?php echo $this->__('Automatic'); ?></option>
            <?php foreach($this->getLanguages() as $language) : ?>
                <?php $selected = ($this->getDestinationLanguage() == $language['value']) ? 'selected="selected"' : null; ?>
                <option value="<?php echo $language['value']; ?>" <?php echo $selected; ?>><?php echo $language['label']; ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <!--<div class="field">
        <button type="button" class="button" onclick="googletranslate_current(); return false;">
            <span><span><?php echo $this->__('Translate Current Value'); ?></span></span>
        </button>
    </div>-->
</div>

<script type="text/javascript">
function googletranslate_change() {

    var source = $('googletranslate_source_language');
    var sourceValue = source.value;
    var sourceLabel = source.options[source.selectedIndex].text;

    var destination = $('googletranslate_destination_language');
    var destinationValue = destination.value;
    var destinationLabel = destination.options[destination.selectedIndex].text;

    var label = '<?php echo Mage::getStoreConfig('catalog/googletranslate/buttonlabel'); ?>';
    label = label.replace('$FROM', sourceLabel);
    label = label.replace('$TO', destinationLabel);

    if(sourceValue != '' && destinationValue != '') {
        $$('.googletranslate_button').each(function(button) {
            button.down('span').update(label);
            button.className = 'googletranslate_button';
            button.disabled = false;
        });
    }
}

/*function googletranslate_current() {
    jQuery('input').each(function() {
        element = jQuery('input[name="' + this.name + '"]');
        focus = element.focused;
        if(focus == true) {
            console.log('Focus: ' + element.name);
        }
    });
}
    
jQuery(document).ready(function() {
    jQuery('input[type=text]').hover(function() {
        console.log('Focus: ' + this.name);
        this.focused = true;
    });

    jQuery('input').blur(function() {
        this.focused = false;
    });
});*/
</script>
